### ISSUE TITLE
guzzle/guzzle is abandoned

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-textextraction#42]
composer require silverstripe/textextraction
Using version ^2.1 for silverstripe/textextraction
...
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

**Comment by robbieaverill** [comment]
Thanks for logging!

We weren't planning to fix this issue in the SS3 release line, but it has been done already for SS4. See https://github.com/silverstripe/silverstripe-textextraction/issues/39.

If you'd like to upgrade it in the 2.x line you're welcome to :)

**Comment by robbieaverill** [comment]
Closing since we no longer support SS3 versions outside of critical bug fixes or security
