### ISSUE TITLE
Temporary files aren't removed, leading to servers running out of space

### ISSUE THREAD

**Issue by indygriffiths** [silverstripe/silverstripe-textextraction#54]
Unsure whether this is a FTS issue or a Text Extractor-specific issue, but during a Solr reindex for a go-live this module was creating thousands of temporary PDF files which caused an 24/7 alert and almost caused the server with a 100GB disk to run out of disk space.

It wasn't exactly clear what [these files were for](https://github.com/silverstripe/silverstripe-textextraction/blob/master/src/Extractor/FileTextExtractor.php#L127) and whether they were still needed, so ended up clearing all PDF files that were older than 30 minutes under the assumption that after 30 minutes they'll have fully been "processed" and aren't needed anymore.

Ideally this module should delete files once processed for a reindex (assuming they're not needed anymore) rather than relying on the OS to clear the `TEMP_DIR` when it feels like it.

**Comment by robbieaverill** [comment]
Seems sensible to me to clean up temp files after they’re not required any more

**Comment by chillu** [comment]
PR at https://github.com/silverstripe/silverstripe-textextraction/pull/55

**Comment by robbieaverill** [comment]
Thanks @ichaber
