### ISSUE TITLE
Incorrect param from exec() passed to implode()

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-textextraction#58]
Look in `PDFTextExtractor::getRawOutput()`. the 3rd param `$err` passed to `exec()` will produce an integer value from `exec()`, being as it is the exit code from the shell invocation of `/usr/local/bin/pdftotext`.

The logic then goes on to pass it as the 2nd param to `implode()` which expects an array, not an int. I believe the original author meant to have passed `$content` instead.

```
exec(sprintf('%s %s - 2>&1', $this->bin('pdftotext'), escapeshellarg($path)), $content, $err);
if ($err) {
    ..

    throw new Exception(sprintf(
        'PDFTextExtractor->getContent() failed for %s: %s',
        $path,
        implode(PHP_EOL, $err) // <-- Here
    ));
}
```

**Comment by phptek** [comment]
Cheers @robbieaverill - any chance of a minor release? Otherwise I need to ref `dev-3` in composer.json to get the patch (or run off my fork)... thanks :-)

**Comment by robbieaverill** [comment]
@phptek I'll leave that to @Cheddam or @maxime-rainville - I think there might be a CWP release in flight and don't want to mess that up

**Comment by maxime-rainville** [comment]
The release will probably be out tomorrowish. We can look at tagging a new release of this module after that.
