### ISSUE TITLE
PHPDoc for default cache lifetime does not match actual default.

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-textextraction#70]
The PHPDoc for the `lifetime` config variable in `SilverStripe\TextExtraction\Cache\FileTextCache\Cache` says "Null is indefinite"
https://github.com/silverstripe/silverstripe-textextraction/blob/25d8a55058f3197a18538bf644ba24e970d63211/src/Cache/FileTextCache/Cache.php#L19-L26

But when saving, the lifetime is given a default value of 3600 for falsey (including null) values.
https://github.com/silverstripe/silverstripe-textextraction/blob/25d8a55058f3197a18538bf644ba24e970d63211/src/Cache/FileTextCache/Cache.php#L68

**Comment by GuySartorelli** [comment]
I would have just raised a PR for this but I'm not sure if the correct move is to try to respect the PHPDoc or just change it to match the current behaviour.

**Comment by emteknetnz** [comment]
Feel free to open a PR to change the phpdoc.  Changing 3600 to something else would be an unexpected behavioural change
